# Generated by Django 4.0.3 on 2022-04-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_featured_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='price',
        ),
    ]
