# Generated by Django 4.0.3 on 2022-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_phones_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['uname'], name='app_account_uname_df9125_idx'),
        ),
    ]
