# Generated by Django 4.0.3 on 2022-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_app_account_uname_df9125_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('uname__gte', 'ali')), name='uname_gte_3'),
        ),
    ]
