# Generated by Django 4.0.3 on 2022-04-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_uname_gte_3'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='uname_gte_3',
        ),
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.CheckConstraint(check=models.Q(('title__gte', 'ali')), name='title_gte_3'),
        ),
    ]
