# Generated by Django 4.0.3 on 2022-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_account_uname_gte_3_posts_title_gte_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
        migrations.RemoveConstraint(
            model_name='posts',
            name='title_gte_3',
        ),
        migrations.RemoveIndex(
            model_name='accounts',
            name='app_account_uname_df9125_idx',
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['uname'], name='accounts_uname_0db77a_idx'),
        ),
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='phones',
            table='phones',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
